version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DKR_ENDPOINT

  build:
    commands:
      - docker build -t app-image .
      - docker tag app-image $DKR_ENDPOINT/app-image:latest
      - docker tag app-image $DKR_ENDPOINT/app-image:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - docker push $DKR_ENDPOINT/app-image:latest
      - docker push $DKR_ENDPOINT/app-image:$CODEBUILD_BUILD_NUMBER
      - printf '[{"name":"app-container","imageUri":"%s"}]' $DKR_ENDPOINT/app-image:latest > imageDefinitions.json
      - printf '[{"ImageUri":"%s"}]' $DKR_ENDPOINT/app-image:latest > imageDetail.json

artifacts:
  files:
    - image*.json
    - taskdef.json
    - appspec.yaml
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json