version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DKR_ENDPOINT

  build:
    commands:
      - docker build -t app-image .
      - docker tag app-image $DKR_ENDPOINT/app-image:latest
      - docker tag app-image $DKR_ENDPOINT/app-image:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - docker push $DKR_ENDPOINT/app-image:latest
      - docker push $DKR_ENDPOINT/app-image:$CODEBUILD_BUILD_NUMBER